### ISSUE TITLE
FullComponents AuctionInfo to show market info once auction is over.

### ISSUE THREAD

**Issue by dblodorn** [ourzora/nft-components#105]
Currently when using the `FullComponents.AuctionInfo` component shows sold for info inconsistently:
I believe this is located to NFT Components and not the Iframe Embed codebase.

Perhaps we should revisit this component, and add some config options for what it renders for different market states.

Not showing here:
https://embed.zora.co/config/0x364547ADfc7a180744D762056Df35eeaEa803EC4/1

Although showing here:
https://embed.zora.co/config/foundation/105683

![Screen Shot 2021-11-30 at 5 15 08 PM](https://user-images.githubusercontent.com/7268786/144153924-2747c9ac-718e-4229-a5f6-e36f06cf93e3.png)

![Screen Shot 2021-11-30 at 5 11 13 PM](https://user-images.githubusercontent.com/7268786/144153643-1ae3576e-7903-45f5-ab4a-cc78909701b9.png)

![Screen Shot 2021-11-30 at 5 11 58 PM](https://user-images.githubusercontent.com/7268786/144153647-333f727d-8273-4759-aa98-4ce97bddf21e.png)

**Comment by dblodorn** [comment]
@iainnash this is tied to the `useBetaIndexer` flag

https://user-images.githubusercontent.com/7268786/144157128-c52cd99f-86a4-4362-a525-69c52b30d108.mov

**Comment by iainnash** [comment]
The useBetaIndexer flag shouldn't affect this rendering, will look into this bug.

**Comment by iainnash** [comment]
Believe this has been fixed.
