### ISSUE TITLE
Supporting Safari on iOS

### ISSUE THREAD

**Issue by scottrepreneur** [ourzora/nft-components#108]
We're not having luck with the `NFTPreview` component working in Safari on iOS for rabbithole.gg. It is working on desktop.

```
<MediaConfiguration
  networkId={networkId}
  style={styleOverride(true)}
>
  <NFTPreview
    id={id}
    showBids={false}
    refreshInterval={5000}
    href={`https://zora.co/${data?.nft?.creator}/${data?.nft?.tokenId}`}
  />
</MediaConfiguration>
```

![pulse-image-1638393222838](https://user-images.githubusercontent.com/1778380/144315010-673989b0-fb3c-4645-8202-0fd0c6e98681.jpg)

**Comment by SouravInsights** [comment]
Hey, @iainnash So after I updated to the latest version, it looks good for safari but is now not working in Firefox and Chrome-based browsers.
