### ISSUE TITLE
NFT preview error in chromium browsers

### ISSUE THREAD

**Issue by scottrepreneur** [ourzora/nft-components#111]
The fix for #108 fixed up Safari support but we're getting issues now on Chromium browsers and Firefox.

- using default IPFS provider/backup gateway

**Comment by iainnash** [comment]
Do you have an idea of what the error is?

**Comment by scottrepreneur** [comment]
`ipfs: video streaming is not allowed` seeing this returned with the 403. Sorry should've included here. Can check out https://staging.rabbithole.gg has the most recent version.

**Comment by iainnash** [comment]
Try upgrading again, seems to work on the example for the latest nft-components library:
https://ourzora.github.io/nft-components/?path=/story/renderer-nftfull--video&args=id:3724
