### ISSUE TITLE
Modify markup in auction info list - fix etherscan link arrow placement.

### ISSUE THREAD

**Issue by dblodorn** [ourzora/nft-components#66]

**Comment by iainnash** [comment]
@dblodorn has this been fixed?

**Comment by dblodorn** [comment]
This is fixed and has been merged into main. We just need to publish a new release on NPM.
https://github.com/ourzora/nft-components/pull/74/commits/cb3c66779f8d6688019ab2a05c2b294314f8c6af

![Screen Shot 2021-10-11 at 4 50 01 PM](https://user-images.githubusercontent.com/7268786/136868230-3fdd5a79-2781-4d2d-bbeb-337f83a8eb36.png)

**Comment by iainnash** [comment]
Fixed
