### ISSUE TITLE
Ideally, we'd forward className props to components so styles can be applied directly

### ISSUE THREAD

**Issue by bjfresh** [ourzora/nft-components#79]
Just a quality-of-life thing, as there are client-side workarounds, but it'd be super if className props were always down to components so eg. we can apply sx={} props to nft-components instances.

eg. https://github.com/styled-components/styled-components/issues/1086

**Comment by iainnash** [comment]
@bjfresh This seems reasonable

I think there was a reason I didn't do this at first but considering we now expose public classnames for styling this should be fine.
